### ISSUE TITLE
Fix merging of NPM package dependencies

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/pywebpack#2]
Similar to https://github.com/inveniosoftware/invenio-assets/blob/master/invenio_assets/npm.py#L70-L99

**Comment by pferreir** [comment]
Am I right to assume that if we get `1.0` and `1.2` of the same package, we should return `1.2`? Should we ignore specs like `>1.0` etc.?

**Comment by lnielsen** [comment]
Good point about the qualifiers! 

I just checked the old code and ``node-semver`` has a function ``semver.max_satisfying`` which seems to completely ignore the qualifiers:

```python
>>> max_satisfying(['1.1', '>1', '<1.2'], '*', True)
'<1.2'
```

In principle ``>1`` ought to be selected if the qualifiers was taken into account, however the returned result do keep the qualifier so I think we can just use it like this. It's not fully correct but properly merging multiple semversions is probably not going to be easy.

**Comment by pferreir** [comment]
OK, I'll take care of that. I don't know if I will resist writing a an extension from `node-semver` that does that properly.
