### ISSUE TITLE
Update Changelog to mention removal of Python 2.7 support

### ISSUE THREAD

**Issue by ThiefMaster** [inveniosoftware/pywebpack#29]
See my comment here https://github.com/inveniosoftware/pywebpack/pull/23#issuecomment-630445124

Too late to fix the releases now unless you are willing to yank 1.0.2 and 1.0.3 and release 1.0.4 / 2.0.0 instead (PyPI should really have a way to apply `python_requires` metadata retroactively!) but let's at least fix the changelog? :)

**Comment by lnielsen** [comment]
CHANGES.rst was updated, but this issue never closed.
