### ISSUE TITLE
Dependency on old `node-semver` package breaks actual `semver` package

### ISSUE THREAD

**Issue by apirogov** [inveniosoftware/pywebpack#38]
I ran into hard-to-debug troubles that in the end were rooted in the problem that

* `node-semver` was using the module name `semver` in version [`0.1.1`](https://github.com/podhmo/python-node-semver/tree/0.1.1)
* This invenio package pulls that version as a dependency

Leading to problems when I installed packages that install the **package** `semver`, which also uses `semver` as module name.

## Expected behavior

No problems when installing [semver](https://github.com/python-semver/python-semver) package

## Solution

* ~~Update to most recent `node-semver` version [0.9](https://github.com/podhmo/python-node-semver/tree/master)~~
* ~~change `semver` to `nodesemver` [here](https://github.com/inveniosoftware/pywebpack/blob/master/pywebpack/helpers.py#L18)~~
* ~~making sure that the updated version is used upstream when installing InvenioRDM from master~~

## EDIT

* We were not the first ones stumbling on the problem with the module clash: https://github.com/podhmo/python-node-semver/issues/39
* Also, consider this: https://github.com/podhmo/python-node-semver/issues/49

Just updating the dependency to `0.9.0` results in *changed behavior* - `node-semver` in newer versions turns out to work with **Python** semver strings, not **JS** ones (what it is used for). Hence simply upgrading yields errors, because versions from a `package.json` such as `^7.9.0` are not valid Python semver strings (different syntax).

A solution would mean migrating to a package that **actually** checks npm-style semver strings, or doing something else.

**Comment by ThiefMaster** [comment]
Just ran into this bug when updating deps in Indico. For now I'll just pin `semver<0.9` but a fixed release wold be grat :)

**Comment by ntarocco** [comment]
> Just ran into this bug when updating deps in Indico. For now I'll just pin `semver<0.9` but a fixed release wold be grat :)

I started working on that, see related PR, but then we had an internal discussion about the expected behaviour, given the changes of the `semver` library.
The only func we use is `max_satisfying`, and now it does not accept any `~` or `^`. In any case, it was completely ignored.
Before we had:
```
In [5]: max_satisfying(["~1.0.0", "2.0.0"], '*', True)
Out[5]: '2.0.0'
```

Now:
```
 [5]: max_satisfying(["~1.0.0", "2.0.0"], '*', True)
Out[5]: 
  File "/Users/nico/.pyenv/versions/pywebpack/lib/python3.9/site-packages/nodesemver/__init__.py", line 333, in __init__
    raise ValueError("Invalid Version: {}".format(version))
ValueError: Invalid Version: ~1.0.0
```

So, the plan would be now to simply strip out any `~`, `^` and replicate the same behaviour as before.
Will this work for you?

**Comment by ThiefMaster** [comment]
After a quick look at your code and ours and even adding a print statement inside `merge_deps`, I don't think we use anything that even calls this.
