### ISSUE TITLE
Dependence on outdated semver.

### ISSUE THREAD

**Issue by andriish** [inveniosoftware/pywebpack#40]
## Describe the bug

The pywebpack 1.2.0 in pywebpack/helpers.py has 
```
from semver import max_satisfying
```
However, the recent versions of `semver`  don't have that function.

The suggested change:
```
from semver import max_ver as max_satisfying
```
or similar.

Tagging Adrian @ThiefMaster , as I observe this behaviour while building Indico.

**Comment by ntarocco** [comment]
Fixed here: https://github.com/inveniosoftware/pywebpack/pull/39
