### ISSUE TITLE
Dependencies needed to run `run-tests.sh`

### ISSUE THREAD

**Issue by pferreir** [inveniosoftware/pywebpack#8]
Namely `pydocstyle`, `check-manifest` and `sphinx`.
Not sure whether I should just dump them into `requirements-devel.txt`. Is that the way you guys normally do it?

**Comment by drjova** [comment]
we usually put them like that https://github.com/inveniosoftware/invenio-base/blob/master/setup.py#L42-L60

**Comment by pferreir** [comment]
Ah, and then you use `pip install -e .[tests]`? OK. Cool. Never mind then.
